using System.Diagnostics.Metrics;

namespace RentifyInfrastructure.Metrics;

public sealed class LlmMetrics
{
    public const string MeterName = "Rentify.LLM";

    private readonly Counter<long> _requests;
    private readonly Counter<long> _failures;
    private readonly Counter<long> _inputTokens;
    private readonly Counter<long> _outputTokens;
    private readonly Histogram<double> _duration;

    public LlmMetrics(IMeterFactory meterFactory)
    {
        var meter = meterFactory.Create(MeterName);

        _requests = meter.CreateCounter<long>("rentify.llm.requests", unit: "{request}", description: "Number of LLM requests.");

        _failures = meter.CreateCounter<long>("rentify.llm.failures", unit: "{failure}", description: "Number of failed LLM requests.");

        _inputTokens = meter.CreateCounter<long>("rentify.llm.input_tokens", unit: "{token}", description: "Number of input tokens sent to the LLM.");

        _outputTokens = meter.CreateCounter<long>("rentify.llm.output_tokens", unit: "{token}", description: "Number of output tokens generated by the LLM.");

        _duration = meter.CreateHistogram<double>("rentify.llm.duration", unit: "ms", description: "Duration of LLM requests.");
    }

    public void RecordRequest(string model, long inputTokens, long outputTokens, double durationMs)
    {
        _requests.Add(1, new KeyValuePair<string, object?>("model", model));

        _inputTokens.Add(inputTokens, new KeyValuePair<string, object?>("model", model));

        _outputTokens.Add(outputTokens, new KeyValuePair<string, object?>("model", model));

        _duration.Record(durationMs, new KeyValuePair<string, object?>("model", model));
    }

    public void RecordFailure(string model)
    {
        _failures.Add(1, new KeyValuePair<string, object?>("model", model));
    }
}
